import Head from "next/head";
import { Lexend } from "next/font/google";
import Image from "next/image";
import { motion } from "framer-motion";
import Header from "./components/header";
import style from "../styles/Home.module.css";
import finance from "../../public/images/main.jpg";
import wallet from "../../public/images/dollar.png";
import piggy from "../../public/images/piggy.jpg";
import data from "../../public/images/data.jpg";
import leaderboard from "../../public/images/leaderboard.png";
import Card from "./components/card";
import Link from "next/link";
import BrandName from "./components/brandname";

const lexend = Lexend({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>StockBuddy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-full flex flex-col">
        <Header />
        <div className="font-sans overflow-x-hidden rounded-b-xl min-h-screen flex items-center shadow-2xl bg-gradient-to-r from-purple-950 via-purple-900 to-purple-950">
          <div className="flex flex-col text-white justify-center items-center h-full w-full">
            <div
              className={`${lexend.className} flex flex-col items-center w-full justify-between`}
            >
              <div className="h-full w-full flex items-center justify-center">
                <Image
                  src={wallet}
                  width="0"
                  height="0"
                  sizes="100vw"
                  className="w-64 h-auto pt-5"
                  placeholder="blur"
                  alt="Wallet"
                />
              </div>
              <div className="h-full p-10 max-w-[100vw] w-full text-left">
                <div className="text-6xl md:text-7xl flex flex-wrap justify-center items-center gap-4 w-full">
                  Invest
                  <motion.div
                    className="uppercase flex font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-purple-400 to-pink-600"
                    animate={{
                      y: [-150, 50, 0],
                      scale: [1.2, 2, 1.2, 1],
                    }}
                  >
                    points
                  </motion.div>
                  and{" "}
                  <motion.div
                    className="uppercase flex font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-purple-400 to-pink-600"
                    animate={{
                      y: [150, -50, 0],
                      scale: [1.2, 2, 1.2, 1],
                    }}
                  >
                    Learn
                  </motion.div>
                  investing.
                </div>
                <div className="flex font-sans justify-center items-center gap-2 text-2xl p-3">
                  <button className={style.button}>LOGIN</button>
                  <button className={style.button}>SINGUP</button>
                </div>
              </div>
            </div>
          </div>

          <div className="flex w-full justify-center items-center p-10 pt-2 md:hidden">
            <Image
              src={finance}
              width="0"
              height="0"
              sizes="100vw"
              className="w-72 h-auto rounded-2xl"
              alt="Finance"
              placeholder="blur"
            />
          </div>
        </div>
        <div className="flex-wrap flex p-10 px-16 gap-10 justify-center lg:justify-between items-center">
          <Card
            src={piggy}
            data={"Invest points to learn investing. Risk Free."}
            count={0}
          />
          <Card
            src={data}
            data={
              "Fundamental data of companies to make an informed investment."
            }
            count={1}
          />
          <Card
            src={leaderboard}
            data={
              "Leaderboard to promote healthy competition."
            }
            count={2}
          />
        </div>
      </main>

      <footer className="flex flex-wrap gap-2 p-3 justify-center items-center rounded-t-2xl border-t-2 text-2xl bg-purple-950 text-white">
        <div className="flex">
          <BrandName/>
        </div>
        <span className="uppercase text-center">
          made possible because of many awesome people. <Link className="underline decoration-dotted hover:no-underline" href={""}>Credits.</Link>
        </span>
        
      </footer>
      <div className="bg-slate-800 flex flex-wrap gap-2 font-semibold text-xl justify-center items-center text-center text-white font-sans w-full h-full p-2">
          Made with <motion.span className="cursor-pointer" whileHover={{scale : 1.2}}>&hearts;</motion.span> by <Link className="underline hover:no-underline" href = "">Soumya Deep Sakar</Link>
        </div>
    </>
  );
}
